### PR TITLE
Add api

### PR DESCRIPTION
**Pull request by Theophileaseh**
Connected the React-Redux application to an existing API to create and remove books in a remote server

### CODE REVIEW

**Review by micheaol — COMMENTED** [review]
Hi @Theophileaseh , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project with Linter not set up correctly.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by BenMukebo — CHANGES_REQUESTED** [review]
### Hi @Theophileaseh,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- No linter errors. ✔️ 
- Gitflow was correctly used.  ✔️   
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [ ] According to the project requirement the `redux-thunk` should be added to the project as a package and used as a middleware. Kindly add this 😉 
- eg:
```
import thunk from 'redux-thunk';

  const store = createStore(
        rootReducer,
        applyMiddleware(thunk)
    );
```

- [ ] The Add book and remove book features should work the same as before even after the refactoring to use the API has been done. 💯 Great job implementing the add book feature 👏🏻  however the removed book does not work yet, I'm not able to delete a book after creating it, kindly fix this  😅 

- [ ] Kindly, it would be nice to add explicit steps for cloning your app, running it locally, and seeing the results displayed in the browser, as this will be of help to non-technical users. You can put the steps to clone and run the project in a new Getting Started section under the project's description. This includes `git clone URL` , `cd.., ...` `npm install` , `npm start` etc.

- The README file It is the first file a person will see when they encounter your project, so it should be fairly brief but detailed. It will make your project stand out from a bunch of others.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by alexander16108 — CHANGES_REQUESTED** [review]
Hi @Theophileaseh , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but some are still not addressed yet.




## Suggested changes
_Check the comments under the review._

AS SUGGESTED BY THE PREVIOUS CODE REVIEWER YOU NEED TO IMPLEMENT THE  CHANGES BELOW 🔽 


 According to the project requirement, the redux-thunk should be added to the project as a package and used as middleware. Kindly add this 😉
eg:
```
import thunk from 'redux-thunk';

  const store = createStore(
        rootReducer,
        applyMiddleware(thunk)
    );
```

- [ ] -  The Add book and remove book features should work the same as before even after the refactoring to use the API has been done. 💯 Great job implementing the add book feature 👏🏻 however the removed book does not work yet, I'm not able to delete a book after creating it, kindly fix this 😅


- [ ] -  Kindly, it would be nice to add explicit steps for cloning your app, running it locally, and seeing the results displayed in the browser, as this will be of help to non-technical users. You can put the steps to clone and run the project in a new Getting Started section under the project's description. This includes git clone URL, cd.., ... npm install, npm start etc.

- The README file It is the first file a person will see when they encounter your project, so it should be fairly brief but detailed. It will make your project stand out from a bunch of others.



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Kingstalux** [comment]
hello @Theophileaseh, kindly fix your linters errors before I proceed with the review

**Comment by Kingstalux** [comment]
Hi @Theophileaseh, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ 

- [ ] You have submitted a project, that has failed linter checks. Kindly fix your linters and submit your project for review

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by AnselemOdims — CHANGES_REQUESTED** [review]
### Hi @Theophileaseh , 
Good job implementing some of the changes requested by the previous reviewer.

## Required Changes ♻️
- [ ] It seems introducing the redux-thunk suggested by the previous reviewer introduced some bugs to the code. Please kindly ensure that you can start the app, add books, and remove books from the store.

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by prolajumokeoni — APPROVED** [review]
Hi @Theophileaseh,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
